server:
  port: 9990
spring:
  application:
    name: USERCLIENT
  cloud:
    zookeeper:
      enabled: true
      connect-string: host219:2181,host223:2181,host224:2181
      discovery:
        root: /services
        register: true
  datasource:
    url: jdbc:oracle:thin:@host233:1521/PROD
    username: tvc_itgs_test
    password: ehl1234
    driver-class-name : oracle.jdbc.driver.OracleDriver
