server:
  port: 9911
spring:
  application:
    name: 查询服务
eureka:
  instance:
    #虚拟主机名称
    virtual-host-name: itgsTest
    #心跳时间间隔
    lease-renewal-interval-in-seconds: 10
    #无心跳多久后,该服务失效
    lease-expiration-duration-in-seconds: 30
    appname: 查询服务
    instance-id: ${spring.application.name}:${random.value}
    
  client:
    service-url:
      #默认的服务注册地址
      defaultZone: http://host236:8761/eureka/,http://host235:8761/eureka/
      